version: '3.1'
services:
  prod-db:
    image: postgres:14-alpine
    container_name: prod-db-container
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: "aston_prod"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_URL: "jdbc:postgresql://localhost:6541/aston_prod"
  dev-db:
    image: postgres:14-alpine
    container_name: dev_db_container
    ports:
      - "6540:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "aston_dev"
      POSTGRES_URL: "jdbc:postgresql://localhost:6540/aston_dev"